USE [W_GnBD]
ALTER INDEX ALL ON MOVFAVORITES
REBUILD;
ALTER INDEX ALL ON USERLOGIN
REBUILD;
ALTER INDEX ALL ON USERAUTHORIZATION
REBUILD;
ALTER INDEX ALL ON NOTIFICATIONMESSAGE
REBUILD;
ALTER INDEX ALL ON NOTIFICATIONEMAILSIGNATURE
REBUILD;
ALTER INDEX ALL ON ASYNCPROCESS
REBUILD;
ALTER INDEX ALL ON ASYNCPROCESSARGUMENT
REBUILD;
ALTER INDEX ALL ON ASYNCPROCESSATTACHMENTS
REBUILD;
ALTER INDEX ALL ON MOVCOMMENTS
REBUILD;
ALTER INDEX ALL ON MOVRATTING
REBUILD;
ALTER INDEX ALL ON MOVUSERPROFILE
REBUILD;
ALTER INDEX ALL ON MOVMOVIES
REBUILD;
ALTER INDEX ALL ON MOVCHARACTERS
REBUILD;
GO